In [1]:
import numpy as np


In [2]:
A=np.array([
    [3,-4,1,5],
    [1,3,-2,5],
    [-2,-3,2,2],
    [-1,5,3,4],
])

In [3]:
B=np.array([7,12,2,17])

In [6]:
try:
    solution = np.linalg.solve(A, B)

    # Unpack the solution
    a, b, c, d = solution

    # Format the output as requested
    print(f"a = {a:.2f} , b = {b:.2f} , c = {c:.2f} , d = {d:.2f}")

except np.linalg.LinAlgError:
    print("The system implies a singular matrix and cannot be solved uniquely.")

a = 0.23 , b = 1.21 , c = 1.01 , d = 2.03


In [9]:
rand_A = np.random.randint(-10, 10, size=(4, 4))
rand_B = np.random.randint(-10, 10, size=4)

In [10]:
print("Matrix A:", rand_A)
print("Vector B:", rand_B)

Matrix A: [[-2 -4  1  0]
 [-5  9 -1  1]
 [ 0  8  2 -4]
 [ 4  8 -4  0]]
Vector B: [ 3  6 -8 -7]


In [11]:
try:
    rand_solution = np.linalg.solve(rand_A, rand_B)
    ra, rb, rc, rd = rand_solution

    print("\nSolution for Random System:")
    print(f"a = {ra:.2f} , b = {rb:.2f} , c = {rc:.2f} , d = {rd:.2f}")

except np.linalg.LinAlgError:
    print("\nThe generated random matrix was singular. Please run again.")


Solution for Random System:
a = -1.06 , b = -0.10 , c = 0.50 , d = 2.06
